### ISSUE TITLE
It booted on unisoc, can you help me

### ISSUE THREAD

**Issue by Namexfr** [ManInTheMirrow/twrp_device_incar_Npad-Pro#1]
Hello I'm a dev like you and i tried to build twrp for my tab(Npad Air), but it doesn't pass the FDL2 before rebooting, any idea about how you fixed that, or what keys you used for vendor_boot

**Comment by Namexfr** [comment]
My tree https://github.com/Fyramiz/device-incar-NpadAir

**Comment by Exepan95** [comment]
Я не разработчик вы тут ошиблись я же написал в тесте что автор не я

чт, 18 июл. 2024 г., 01:28 Namexfr ***@***.***>:

**Comment by Exepan95** [comment]
I'm not a developer, I indicated the original author in the form of github
because I'm not good at programming

чт, 18 июл. 2024 г., 01:30 Namexfr ***@***.***>:

**Comment by Fyramiz** [comment]
Who is the original author?

**Comment by Exepan95** [comment]
In GitHub There

чт, 18 июл. 2024 г., 17:04 Mbark Draoui ***@***.***>:

**Comment by Fyramiz** [comment]
What repository if you have it?

**Comment by Exepan95** [comment]
Nope sorry

чт, 18 июл. 2024 г., 17:22 Mbark Draoui ***@***.***>:

**Comment by Fyramiz** [comment]
Okey 😕

**Comment by Fyramiz** [comment]
How tf can i close an issue???

**Comment by Namexfr** [comment]
I was using the wrong GitHub account, now I can delete the issue
